name: fine-py2
channels:
  - conda-forge
dependencies:
  - python=2.7
  - astroML=0.4.1
  - metis
  - numpy
  - pandas
  - pytest=3.6
  - scikit-learn==0.19.2
  - scipy
  - statsmodels
  - pip
  - pip:
    - ipython
    - matplotlib==1.3.1
    - mca==1.0
    - metis==0.2a1
    - multiprocess
    - networkx==1.11
    - openpyxl==2.5.14
    - python-louvain
    - seaborn==0.8.1
    - simplejson
    - xlrd==1.1
    - git+https://github.com/tonysyu/mpltools
# then get the following file (no setup.py available)
# wget https://raw.githubusercontent.com/jbkinney/13_deft/master/deft.py







