name: fine-py2
channels:
  - conda-forge
dependencies:
  - python=2.7
  - astroML=0.4.1
  - metis
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - pip:
    - matplotlib==1.4
    - metis==0.2a1
    - networkx==1.11
    - python-louvain
    - pytest==3.6
    - xlrd==1.1
    - git+https://github.com/tonysyu/mpltools
# then get the following file (no setup.py available)
# wget https://raw.githubusercontent.com/jbkinney/13_deft/master/deft.py







