name: fine-py2
channels:
  - conda-forge
dependencies:
  - python=2.7
  - astroML=0.4.1
  - metis
  - numpy
  - pandas
  - scikit-learn==0.19.2
  - scipy
  - statsmodels
  - pip
  - pip:
    - matplotlib==1.3.1
    - metis==0.2a1
    - networkx==1.11
    - python-louvain
    - pytest==3.6
    - seaborn==0.8.1
    - simplejson
    - xlrd==1.1
    - git+https://github.com/tonysyu/mpltools
# then get the following file (no setup.py available)
# wget https://raw.githubusercontent.com/jbkinney/13_deft/master/deft.py







