site_name: quafing Documentation
repo_url: https://github.com/SDCCA/quafing
repo_name: quafing

nav:
  - Getting started: 
    - About quaffing: index.md
    - Installation: setup.md
  #- Usage:
  #  - usage_split.md
  #  - usage_daskml.md
  #  - usage_dnn.md
  #- Examples: 
  #  - Covert a nested DataFrame to a Dataset: notebooks/example_read_from_one_df.ipynb
  #  - Align multiple DataFrames to a Dataset: notebooks/example_read_from_multiple_df.ipynb
  #  - Parallelly training sklearn models with dask-ml: notebooks/example_daskml.ipynb
  #  - Parallelly training DNN with Tensorflow: notebooks/example_dnn.ipynb
  - Contributing:
    - Contributing guide: CONTRIBUTING.md
    - Code of Conduct: CODE_OF_CONDUCT.md
  - Change Log: CHANGELOG.md
  - API Reference: reference/


theme:
  name: material
  custom_dir: docs/notebooks/download_button
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: green
      accent: white

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: pink
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  
plugins:
- mkdocs-jupyter:
    include_source: True
    remove_tag_config:
      remove_input_tags:
        - hide_in_docs
- include-markdown
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          members_order: source
          show_source: false
          show_signature: true
          inherited_members: true  # https://github.com/mkdocstrings/python/issues/40
          show_if_no_docstring: True
          signature_crossrefs: true
          docstring_section_style: table
          show_submodules: True
          show_root_heading: false
          show_root_toc_entry: false
          show_root_full_path: false
          show_object_full_path: false
          show_symbol_type_heading: true  # currently only available for insiders
        import:
          - https://docs.python.org/3/objects.inv
          - https://docs.pydantic.dev/latest/objects.inv
          - https://geopandas.org/en/stable/objects.inv
          - https://pandas.pydata.org/pandas-docs/stable/objects.inv
          - https://docs.xarray.dev/en/stable/objects.inv
- gen-files:  # Auto-generate API reference files
    scripts:
      - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index

extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

watch:
- src