name: lint

on: [push]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: fine
          environment-file: environment.yml
          use-mamba: true
      - name: Install dev dependencies
        run: |
          python -m pip install .[dev]
      - name: Check style against standards using prospector
        run: prospector
      - name: Check import order
        run: isort --check-only fine --diff