name: build and test

on: [push]

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ] #, 'macos-latest', 'windows-latest' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: fine
          environment-file: environment.yml
          use-mamba: true
      - name: Install test tools
        run: |
          python -m pip install pytest pytest-cov pycodestyle
      - name: Run tests
        run: |
          python -m pytest -v